### ISSUE TITLE
Parallel execution

### ISSUE THREAD

**Issue by falcaopetri** [slhck/ffmpeg-normalize#159]
**Is your feature request related to a problem? Please describe.**
Normalizing a large set of audios can be really slow since they are processed one at a time.

**Describe the solution you'd like**
It would be nice to have parallel processing in `FFmpegNormalize`.

**Possible approach**
I did a superficial check, but it seems that it's enough to complement `FFmpegNormalize.add_media_file` and `FFmpegNormalize.run_normalization` with parallel support.

Since there is already a heavy usage of `tqdm`, we could take advantage of `process_map`/`thread_map` from [`tqdm.contrib.concurrent`](https://tqdm.github.io/docs/contrib.concurrent/).

Implementation suggestion:

1. `FFmpegNormalize.add_media_file`: it could accept `input_file`/`output_file` both as single elements (current behavior) and as lists (of same length). Then actually creating the `MediaFile` could be done using `process_map`/`thread_map`.
    - [CLI](https://github.com/slhck/ffmpeg-normalize/blob/654e2f030706f972eea2c57ffc49db419761f360/ffmpeg_normalize/__main__.py#L542) could be changed to use this batch version.
2. `FFmpegNormalize.run_normalization`: could be refactored to use `process_map`/`thread_map`.

Of course, we could keep current behavior, and only apply parallelization if requested (e.g., `--parallel`). tqdm's `max_workers`/`chunksize` should also be customizable through `--max-workers`/`--chunksize`.

I'm not sure if it's obvious upfront whether multiprocessing or multi-threading would be faster, but we could run some performance benchmarks and also tune `max_workers`/`chunksize` to provide some default values.

The only issues I see are:
- with logging syncronization. I've heard about, but not used, the [multiprocessing-logging](https://github.com/jruere/multiprocessing-logging) lib.
- with tqdm usage inside `MediaFile.run_normalization` (first and second passes). The easier approach would probably be to disable it.

If the proposal makes sense, I could submit a PR with this feature.

**Comment by slhck** [comment]
Thanks for your suggestion. Parallelization should improve the speed if you're handling multiple files at once. I usually just default to GNU `parallel` if a tool doesn't natively support parallelization, but it would be nice to have this feature in `ffmpeg-normalize`. Here's a quick benchmark:

```
➜ hyperfine 'ffmpeg-normalize -f test.wav test.wav test.wav'
Benchmark 1: ffmpeg-normalize -f test.wav test.wav test.wav
  Time (mean ± σ):     23.271 s ±  0.050 s    [User: 22.849 s, System: 0.344 s]
  Range (min … max):   23.197 s … 23.365 s    10 runs

➜ hyperfine 'parallel ffmpeg-normalize -f {} ::: test.wav test.wav test.wav'
Benchmark 1: parallel ffmpeg-normalize -f {} ::: test.wav test.wav test.wav
  Time (mean ± σ):      8.228 s ±  0.092 s    [User: 23.567 s, System: 0.554 s]
  Range (min … max):    8.150 s …  8.397 s    10 run
```

All your proposals sound reasonable. I personally would prefer to have parallelization be on *by default*, since it will cause speedups for most users, and we don't have to deal with any particular race conditions when normalizing a set of input files. 
There *should* be a check though, making sure that the same set of input/output files is not processed more than once.

You could add a CLI option `--threads` that defaults to `multiprocessing.cpu_count()`; if users want serial execution, that option could be set to 1.

Thank you for proposing to work on a PR — happy to review it once it's ready!

**Comment by slhck** [comment]
Closing this as not planned, PRs are welcome.

I suggest using GNU `parallel` for parallelization.
