### ISSUE TITLE
Why does EBU normalized output default to 192khz?

### ISSUE THREAD

**Issue by mojoba** [slhck/ffmpeg-normalize#177]
I read that input should be upsampled to 4x the input sample rate for EBU normalization but afterwards, is there a loss of quality to downsample back to the original sample rate e.g. 44.1khz or 48khz?

**Comment by mojoba** [comment]
Wait a second, just checked the output files and the output sample rate is the same as the input sample rate - 48khz in this case.

**Comment by slhck** [comment]
The output sample rate is changed to 192 kHz for accurate peak detection. Detecting accurate peaks is not possible at the original sample rate due to the Nyquist theorem, more info here: https://techblog.izotope.com/2015/08/24/true-peak-detection/.

I am not sure why your output is at the original input sample rate. That should not be the case when using the loudnorm filter without any additional options. Can you please show a reproducible example?

**Comment by slhck** [comment]
Actually, you're right, this behavior seems to have changed. I will update the code and docs respectively.

**Comment by slhck** [comment]
Done in 636b2bedbbab03a0628fe483381e707cd9bafae9. Now the warning will only be printed in the specific case that dynamic mode is forced by ffmpeg or the user.
