### ISSUE TITLE
When running on a folder of mp3s, nearly all of them report loudness range larger than the loudness range target

### ISSUE THREAD

**Issue by looeee** [slhck/ffmpeg-normalize#240]
I want to normalize a folder of mp3s that will be used for background music in a cafe. The goal is to avoid large jumps in loudness between, or during songs. 

When running on folder of mp3s with the command:

```
 ffmpeg-normalize ./ORIG/*.mp3 -c:a libmp3lame -b:a 320k 
```

I get loads of warnings like following, with different values for each file: 

```
WARNING: Input file had loudness range of 10.3. This is larger than the loudness range target (7.0). Normalization will revert to dynamic mode. Choose a higher target loudness range if you want linear normalization. Alternatively, use the --keep-loudness-range-target or --keep-lra-above-loudness-range-target option to keep the target loudness range from the input.
```

In the Readme, I can see these options:

```
-lrt LOUDNESS_RANGE_TARGET, --loudness-range-target LOUDNESS_RANGE_TARGET: EBU Loudness Range Target in LUFS (default: 7.0).

Range is 1.0 - 50.0.

--keep-loudness-range-target: Keep the input loudness range target to allow for linear normalization.

--keep-lra-above-loudness-range-target: Keep input loudness range above loudness range target.

LOUDNESS_RANGE_TARGET for input loudness range <= LOUDNESS_RANGE_TARGET or
keep input loudness range target above LOUDNESS_RANGE_TARGET.
as alternative to --keep-loudness-range-target to allow for linear normalization.
```

However, it's not at all clear to me what the difference between these is, or why I would choose one over another. 
Should I run through all the files, check for the largest loudness range, then set `-lrt LARGEST_LOUDNESS_RANGE`? 

Or should I chose `--keep-loudness-range-target` or `--keep-lra-above-loudness-range-target`, and if so, which of them?

**Comment by slhck** [comment]
In principle, you can ignore the warning and let the algorithm perform the normalization with dynamic mode. If the results sound okay to you, then it's fine. This will perform “compression” on the input signal to reach the target loudness, thus avoiding large volume jumps.

For other cases, i.e. to preserve the dynamic range and just shift the loudness, users want linear mode. For this, the settings have to be chosen such that the target loudness range is equal to or larger than the input loudness range. That's why there's a warning, because the filter chooses its mode implicitly — and it's not always clear when this happens.

If you want linear mode (which I think you don't, according to your use case), to increase the target loudness range to the input loudness range (i.e., to avoid normalization with dynamic mode), you can pass the `--keep-lra-above-loudness-range-target` option. This will always automatically set the target loudness range to the input's loudness range to avoid reverting to dynamic mode.

PS: Over time, options have become more complex to handle special cases that are not directly covered by the filter. If you have a suggestion on how to make these warnings or the README more user-friendly, please let me know (or propose a PR).
