### ISSUE TITLE
Error When Using an Apostrophe ior Ampersand in Pathname

### ISSUE THREAD

**Issue by mtbernier** [slhck/ffmpeg-normalize#250]
**:warning: Please read this carefully and edit the example responses! If you do not fill out this information, your bug report may be closed without comment.**

**Checklist** (please tick all boxes)
- [x] I am using the latest version of `ffmpeg-normalize` (run `pip3 install --upgrade ffmpeg-normalize`)
- [x] I am using the latest stable version of `ffmpeg` or a recent build from Git master

**Expected behavior**
I expected the program to create the default folder named "normalized" in the folder where the source mp3 file existed and the normalized version of the mp3 to be place in the created subfolder.

**Actual behavior**
What happened?
Received warning "WARNING: Output file 'normalized\Daniel.mp3' already exists, skipping. Use -f to force overwriting.".  The file named  in the warning did not exist before or after running the command. Reran the command after adding "-f" (force) to the command line.  The result was no  warning message but the "nomalized" named subfolder and the normalized mp3 file were not created.   I ran a batch file with 300 'ffmpeg-normalize" command lines. The issue occurred  for every command where the folder containing the source file had an apostrophe (') and/or an apersand (&) in its name.

**Command**
The exact command you were trying to run:

```
ffmpeg-normalize "C:\Users\mark\Music\Elton John - Don't Shoot Me\Daniel.mp3" -nt peak -t 0 -c::amp3 -ext mp3
ffmpeg-normalize "C:\Users\mark\Music\Genesis - Wind & Wuthering\Afterglow.mp3" -nt peak -t 0 -c::a mp3 -ext mp3
```

Any output you get when running the command with the `--debug` flag:

```
EBUG: Running command: ['C:\\Program Files\\ffmpeg\\bin\\ffmpeg.EXE', '-filters']
WARNING: Output file 'normalized\Daniel.mp3' already exists, skipping. Use -f to force overwriting. 
DEBUG: Running command: ['C:\\Program Files\\ffmpeg\\bin\\ffmpeg.EXE', '-filters']
WARNING: Output file 'normalized\Afterglow.mp3' already exists, skipping. Use -f to force overwriting.
```

**Environment (please complete the following information):**
- [Windows 10 Pro OS build	19045.3693 ] Your operating system
- [ Python] Your Python version / distribution (`python3 --version` or `python --version`)
- [N-111033-gf11515c77f-20230607
![commands](https://github.com/slhck/ffmpeg-normalize/assets/151862021/3a524127-d173-41be-82fe-7c288252d0a0)
 ] Your ffmpeg version (`ffmpeg -version`)

**Comment by slhck** [comment]
Thanks for reporting this. I am afraid this is not the entire debug log, can you please post the full one?

**Comment by mtbernier** [comment]
FYI The complete debug file did not appear until I added the "-f" option to the commmand line. When you pipe the sreen output to a text file the file is empty. I had to copy the debug output from the screen and paste it in  the attached text files.The location in the text files where you see 3 blank lines in a row, reprensent 200+, 200+ and 350+ respectively of blank lines of output on the screen .  Minor flaws just an incxonvenience :-)
[Afterglow-debug.txt](https://github.com/slhck/ffmpeg-normalize/files/13480603/Afterglow-debug.txt)
[Daniel-Debug.txt](https://github.com/slhck/ffmpeg-normalize/files/13480604/Daniel-Debug.txt)

**Comment by slhck** [comment]
Thanks for the logs!

When I read the first one I see:

```
DEBUG: Moving temporary file from C:\Users\mark\AppData\Local\Temp\tmpxqmk81jl\out.mp3 to normalized\Afterglow.mp3
DEBUG: Normalization finished
INFO: Normalized file written to normalized\Afterglow.mp3

C:\Users\mark\Music>
```

To me this implies that `C:\Users\mark\Music\normalized\Afterglow.mp3` should have been created. There is nothing special about apostrophes and ampersands as far as I know, since I am forwarding the commands as-is to the Python subprocess functions, which take in just a file name and _should_ do it in an OS-independent way. I don't have a Windows machine to test with at the moment though.

Note that the `normalized` folder is created relative to your current working directory, not relative to the file(s) you are processing.

If you get an error about the file already being there, are you 100% sure that it's not possibly another file with the same name already placed in the directory, e.g. from another album?

What you could do instead is specify the exact output file name directly in your batch file, and see if that works, i.e., use the `-o` option to specify explicitly where you want the file to be written. Does that work?

**Comment by slhck** [comment]
Great, glad you figured out the issue.
