### ISSUE TITLE
Mutliple files on windows (powershell or command line)

### ISSUE THREAD

**Issue by Nekromancer** [slhck/ffmpeg-normalize#28]
Hey,

Your script is working for single file perfectly, but when using `ffmpeg-normalize -vuo *.mp4` i get an error `2017-05-12 11:22:09,763 - ffmpeg_normalize - ERROR - file *.mp4 does not exist, will skip`.

It's working fine on WSL

**Comment by slhck** [comment]
Does this only affect PowerShell? It should work in CMD.exe.
I don't have Windows available to test, nor have I ever used PowerShell.

**Comment by Nekromancer** [comment]
Unfortunetely it does not work in cmd. 
![cmd screenshot](http://i.imgur.com/k8aphQB.png)

**Comment by slhck** [comment]
Thanks for reporting that. I'll check once I have access to a Windows machine. I've mostly used Cygwin or similar environments.

**Comment by michaelcrossland** [comment]
It does not  work because if you have more then on file in a directory on
Windows you most do something like "for /r  (*.mp4) or ("*.mp4") if the
file names have spaces in them. The /r tells cmd.exe or PowerShell to
recursively look through all files and subdirectories and files.
It doesn't have anything to do with the script. It a short coming of
Windows and it old Legacy code that it still supports.

**Comment by slhck** [comment]
Oh okay, yeah that makes sense. I forgot that I wasn't parsing the glob myself. As you said, it's probably a matter of looping through the files externally. The `*.mp4` is a Unix-style shell idiosyncracy anyway, so it's not part of the program.

**Comment by michaelcrossland** [comment]
If you would like some example code as to do what you want to do I'd be
glad to post some here or email you some in plain text not in a bat or com
or ps script.

**Comment by Nekromancer** [comment]
@michaelcrossland That would be great!

**Comment by michaelcrossland** [comment]
Okay I'll post some to this thread as long as it's still open to do that
here later today once I get done with work.

**Comment by Nekromancer** [comment]
Awsome, thanks in advance

**Comment by michaelcrossland** [comment]
Okay here is a script that I use to run the script to level the news
programs that my Father wants to see and keep. I'll make comments off to
the side with // before what I type. I have 2nd one as well that I use to
do MP3's and other audio files as well. I'll post that one in a new post
here after this one. Okay here we go.


           CODE
<-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------->
// As a note this is a batch file code so if you want to run this by
inputting it in CMD.exe or PS please remove the %% and just use one %.
Otherwise it will just tell you you are a no good SOB. ;-)


:top // This just a function call so that I can have my loops call back
here where those subfunction calls as done.
setlocal enableDelayedExpansion // You will need this because it tells
CMD.exe that there will be something other then numbers inside some of //
the variables
cd /d "S:\seens2" // this is just telling CMD where to go can be set to any
drive and dir. Oh it's a good idea to use "" around commands so that if //
there spaces windows don't puck on what you give it. You can on commands
like CD get away with out them.
*for %%a in ("NBC 5*.mp4") do goto :NBC5* // Okay here is what you where
missing. Here I'm telling CMD for every file in this dir if it has ("NBC
//5*.mp4") in it's name then stop and goto the NBC5 Subfunction if not go
to the next and so on and so on.
for %%a in ("NBC Nightly News*.mp4") do goto :Nightly
for %%a in (Meet*.mp4) do goto :Meet
cd /d "D:\iTube Studio Downloaded" // this is just going to a new 2nd dir I
may have files in as well.
for /R %%a in ("NBC Nightly News*.mp4") do goto :Nightly2
for /R %%a in ("Dateline -*.mp4") do goto :Dateline
for /R %%a in (Meet*.mp4) do goto :Meet2
GOTO :EOF  // Now this part is really important you need to add the Goto
:EOF other wise it will keep running in a loop. All this doing saying if
//you get here windows stop running the script and close the window if you
run it from a *.bat file.

:Nightly
Set conv="S:\seens2"
set con="Z:\News\NBC\NBC Nightly News"
rem cd /d "D:\seens"
for %%a in ("NBC Nightly News*.mp4") do set FileName="%%~nxa" // this one
get the full filename of the file that has what ever I asked for in //the
() Remember if your file name has spaces in it you have to enclose it in ""
otherwise it will try to match just first part then the next and so //on.
set FileName2=%FileName:"=%  // This takes what's in variable FileName and
then removes the "" from it.
*for /F "delims=" %%A in ("%FileName2%") do set FILENAME3=%%~nxA // This
one takes and cleans the name up so it's just the file //name not the full
path and file name.*
*for /F "delims=" %%A in ("%FILENAME3%") do set FILENAME4=%%~nA // this is
where the *setlocal enableDelayedExpansion comes into //uses. No this one
remove the ext from the file name I do that so I van use it if I rename a
file that is MKV to MP4 with out having to do //anything other then set
what ext I want later on.
*ffmpeg-normalize -u -v -l -32.5 -a aac -e "-b:a 96k" "%FILENAME3%"* // Now
here I'm taking the filename that was parced in the other 3 Sets.
del /q "%FILENAME3%" // here I'm deleting the non-leveled file.
IF %ERRORLEVEL% EQU 0 (move "normalized-%FILENAME3%" "%FILENAME3%") ELSE
(GOTO :FUCK) // here I'm checking to see if the //delete worked right. If
it did then it will move the new normalized file to the original file name
so it can be used in the rest of the script with out having to reset what
is all ready in the Variables.If the delete does not work sorry about the
subfunction name but it goes //there pauses the script for 30 mins so I can
see what happen and with any luck fix it.
ffmpeg -y -i "%FILENAME3%" -codec:v libx264 -pix_fmt yuv420p -profile:v
high -level:v 4.0 -preset ultrafast -b:v 1175k -threads 0 -pass 1
-passlogfile NBC.log -an -f mp4 NUL // Okay here I take the leveled file
and do 2 pass re-encode on it so that plex on PS3 will play it right.
ffmpeg -i "%FILENAME3%" -codec:v libx264 -pix_fmt yuv420p -profile:v high
-level:v 4.0 -preset ultrafast -b:v 1175k -threads 0 -c:a copy -pass 2
-passlogfile NBC.log "Z:\News\NBC\NBC Nightly News\%FILENAME3%" // this is
the 2nd pass of the re-encode. If you like more info let //know.
del /q "%FILENAME3%" // here I just deleting the leveled file from the dir.
As in the 2nd part I have the output goto my NAS drive.
C:\curl\bin\wget.exe --output-document tmp1.txt --quiet
http://192.168.1.11:32400/library/sections/4/refresh // here I'm just
calling Plex's API to //check for new files in a Library. In this case the
NBC Library. if want more info please ask.
del /q tmp1.txt // here i'm deleting the temp file I had wget make that has
zip in it. oh you should use the /q with delete because it will not ask
//yes or no about removing files. Otherwise it will stop your script and
ask you if you want to do that YES or NO.
goto :top // And here I'm having go back to the top function to see if
there are more file to be worked over or not. The rest is just the rest of
the //script.

:Nightly2
Set conv="S:\seens2"
set con="Z:\News\NBC\NBC Nightly News"
rem cd /d "D:\seens"
for %%a in ("NBC Nightly News*.mp4") do set FileName="%%~nxa"
set FileName2=%FileName:"=%
for /F "delims=" %%A in ("%FileName2%") do set FILENAME3=%%~nxA
for /F "delims=" %%A in ("%FILENAME3%") do set FILENAME4=%%~nA
ffmpeg-normalize -u -v -l -32.5 -a aac -e "-b:a 96k" "%FILENAME3%"
del /q "%FILENAME3%"
IF %ERRORLEVEL% EQU 0 (move "normalized-%FILENAME3%" "%FILENAME3%") ELSE
(GOTO :FUCK)
ffmpeg -y -i "%FILENAME3%" -codec:v libx264 -pix_fmt yuv420p -profile:v
high -level:v 4.0 -preset ultrafast -b:v 1175k -threads 0 -pass 1
-passlogfile NBC.log -an -f mp4 NUL
ffmpeg -i "%FILENAME3%" -codec:v libx264 -pix_fmt yuv420p -profile:v high
-level:v 4.0 -preset ultrafast -b:v 1175k -threads 0 -c:a copy -pass 2
-passlogfile NBC.log "Z:\News\NBC\NBC Nightly News\%FILENAME3%"
del /q NBC.log-0.log
del /q "%FILENAME3%"
C:\curl\bin\wget.exe --output-document tmp1.txt --quiet
http://192.168.1.11:32400/library/sections/4/refresh
del /q tmp1.txt
goto :top

:Meet
Set conv="D:\iTube Studio Downloaded"
set con="Z:\News\NBC\Meet the Press"
for %%a in ("Meet the Press*.mp4") do set FileName="%%~nxa"
set FileName2=%FileName:"=%
for /F "delims=" %%A in ("%FileName2%") do set FILENAME3=%%~nxA
for /F "delims=" %%A in ("%FILENAME3%") do set FILENAME4=%%~nA
ffmpeg-normalize -u -v -l -32.5 -a aac -e "-b:a 96k" "%FILENAME3%"
del /q "%FILENAME3%"
IF %ERRORLEVEL% EQU 0 (move "normalized-%FILENAME3%" "%FILENAME3%") ELSE
(GOTO :FUCK)
ffmpeg -y -i "%FILENAME3%" -codec:v libx264 -pix_fmt yuv420p -profile:v
high -level:v 4.0 -preset ultrafast -b:v 1175k -threads 0 -pass 1
-passlogfile NBC.log -an -f mp4 NUL
ffmpeg -i "%FILENAME3%" -codec:v libx264 -pix_fmt yuv420p -profile:v high
-level:v 4.0 -preset ultrafast -b:v 1175k -threads 0 -c:a copy -pass 2
-passlogfile NBC.log "Z:\News\NBC\Meet The Press\%FILENAME3%"
del /q NBC.log-0.log
del /q "%FILENAME3%"
C:\curl\bin\wget.exe --output-document tmp1.txt --quiet
http://192.168.1.11:32400/library/sections/4/refresh
del /q tmp1.txt
goto :top

:Meet2
Set conv="D:\iTube Studio Downloaded"
set con="Z:\News\NBC\Meet the Press"
for %%a in ("Meet the Press*.mp4") do set FileName="%%~nxa"
set FileName2=%FileName:"=%
for /F "delims=" %%A in ("%FileName2%") do set FILENAME3=%%~nxA
for /F "delims=" %%A in ("%FILENAME3%") do set FILENAME4=%%~nA
ffmpeg-normalize -u -v -l -32.5 -a aac -e "-b:a 96k" "%FILENAME3%"
del /q "%FILENAME3%"
IF %ERRORLEVEL% EQU 0 (move "normalized-%FILENAME3%" "%FILENAME3%") ELSE
(GOTO :FUCK)
ffmpeg -y -i "%FILENAME3%" -codec:v libx264 -pix_fmt yuv420p -profile:v
high -level:v 4.0 -preset ultrafast -b:v 1175k -threads 0 -pass 1
-passlogfile NBC.log -an -f mp4 NUL
ffmpeg -i "%FILENAME3%" -codec:v libx264 -pix_fmt yuv420p -profile:v high
-level:v 4.0 -preset ultrafast -b:v 1175k -threads 0 -c:a copy -pass 2
-passlogfile NBC.log "Z:\News\NBC\Meet The Press\%FILENAME3%"
del /q NBC.log-0.log
del /q "%FILENAME3%"
C:\curl\bin\wget.exe --output-document tmp1.txt --quiet
http://192.168.1.11:32400/library/sections/4/refresh
del /q tmp1.txt
goto :top

:NBC5
cd /d "S:\seens2"
for %%a in ("NBC 5*.mp4") do set FileName="%%~nxa"
set FileName2=%FileName:"=%
for /F "delims=" %%A in ("%FileName2%") do set FILENAME3=%%~nxA
for /F "delims=" %%A in ("%FILENAME3%") do set FILENAME4=%%~nA
ffmpeg-normalize -u -v -l -32.5 -a aac -e "-b:a 96k" "%FILENAME3%"
del /q "%FILENAME3%"
IF %ERRORLEVEL% EQU 0 (move "normalized-%FILENAME3%" "%FILENAME3%") ELSE
(GOTO :FUCK)
ffmpeg -y -i "%FILENAME3%" -codec:v libx264 -pix_fmt yuv420p -profile:v
high -level:v 4.0 -preset ultrafast -b:v 1175k -threads 0 -pass 1
-passlogfile NBC.log -an -f mp4 NUL
ffmpeg -i "%FILENAME3%" -codec:v libx264 -pix_fmt yuv420p -profile:v high
-level:v 4.0 -preset ultrafast -b:v 1175k -threads 0 -c:a copy -pass 2
-passlogfile NBC.log "Z:\News\NBC\NBC 5 News\%FILENAME3%"
del /q NBC.log-0.log
del /q "%FILENAME3%"
C:\curl\bin\wget.exe --output-document tmp1.txt --quiet
http://192.168.1.11:32400/library/sections/4/refresh
del /q tmp1.txt
goto :top

:Dateline
Set conv="D:\iTube Studio Downloaded"
set con="Z:\News\NBC\Dateline NBC"
rem cd /d %conv%
for /R %%a in ("Dateline*.mp4") do set FileName="%%~nxa"
set FileName2=%FileName:"=%
for /F "delims=" %%A in ("%FileName2%") do set FILENAME3=%%~nxA
for /F "delims=" %%A in ("%FILENAME3%") do set FILENAME4=%%~nA
ffmpeg-normalize -u -v -l -32.5 -a aac -e "-ac 2 -b:a 96k" "%FILENAME3%"
del /q "%FILENAME3%"
IF %ERRORLEVEL% EQU 0 (move "normalized-%FILENAME3%" "%FILENAME3%") ELSE
(GOTO :FUCK)
ffmpeg -y -i "%FILENAME3%" -codec:v libx264 -pix_fmt yuv420p -profile:v
high -level:v 4.0 -preset ultrafast -b:v 434k -threads 0 -pass 1 -an
-passlogfile NBC.log  -f mp4 NUL
ffmpeg -i "%FILENAME3%" -codec:v libx264 -pix_fmt yuv420p -profile:v high
-level:v 4.0 -preset ultrafast -b:v 434k -threads 0 -c:a copy -pass 2
-passlogfile NBC.log  "dpl2-%FILENAME3%"
move "dpl2-%FILENAME3%" "Z:\News\NBC\Dateline NBC\%FILENAME3%"
del /q "%FILENAME3%"
del /q NBC.log-0.log
C:\curl\bin\wget.exe --output-document tmp1.txt --quiet
http://192.168.1.11:32400/library/sections/4/refresh
del /q tmp1.txt
goto :top

:Fuck // This is the sub function that gets called to stop the script so
that I can try to fix something if it's gone wrong.
Echo Something fucked up, please check the output. // here I'm just having
it print on screen what is after the echo command.
timeout /t 1800 // here it's stopping the script for 30 minutes in seconds.
GOTO :EOF // once the timer runs out or I hit a key it calls for the nd of
file or telling windows to stop running the script and close the window if
//run from a batch file.

**Comment by michaelcrossland** [comment]
chdir /d "D:\tunes" // just get's me into the right dir you can change to
where ever.
SET /P dec=Set the dB drop here: // this is to set the dB drop or rise to
where ever level you would like. I use -12 or -5 dB when working with just
audio files.
set "FileName=" // just setting varables for later.
set "FileName2="
set "FileName3="
set "FileName4="
echo Nul >"filelist.txt" // here I'm makeing a file called filelist.txt
with the fist line set to Nul
dir /b *.mp3 *.m4a *.flac *.org *.wav *.ac3 >> filelist.txt // here I'm
having a dir listing of just the files with the exts in the list added to
the file.
for /f "delims=" %%i in (filelist.txt) do set file="%%~nxi" // here we are
reading the file line by line and the last line get put into varable
FileName
for %%i in (%file%) do set ext=%%~xi // Here I'm having CMD look at the ext
in the varable file so that only ext I want to work with will be worked on
all other ext will be not seen.
if /i "%ext%"==".mp3" goto next // here I'm just seeing if the ext matchs
what I put into the right side.
if /i "%ext%"==".m4a" goto next // here I'm just seeing if the ext matchs
what I put into the right side.
if /i "%ext%"==".flac" goto next // here I'm just seeing if the ext matchs
what I put into the right side.
if /i "%ext%"==".org" goto next // here I'm just seeing if the ext matchs
what I put into the right side.
if /i "%ext%"==".wav" goto next // here I'm just seeing if the ext matchs
what I put into the right side.
if /i "%ext%"==".ac3" goto next // here I'm just seeing if the ext matchs
what I put into the right side. Now because the script is running ffmpeg
you can handle any ext that ffmpeg can.
del /f /q filelist.txt // here I delete the txt file so that it'm made new.
goto :EOF // here end the script when no more exts match.

:next
set FileName2=%file:"=% here wee take the file name set in varale file and
remove any "" that maybe around it due to spaces.
for /F "delims=" %%A in ("%FileName2%") do set FILENAME3=%%~nxA // here we
set the file name and ext only in the varable here.
for /F "delims=" %%A in ("%FILENAME3%") do set FILENAME4=%%~nA // here is a
tag along from other script caod but this set the varable here to just that
file name no ext.
ffmpeg-normalize -o -u -v -l %dec% -a aac -e "-ac 2 -b:a 96k" %file% // Now
two things to point out here one in the -e "" I have added -ac 2 that is
because ffmpeg don't down mix 5.1 or 7.1 //audio right if it don't know how
many output chanaels you are useing. the 2nd thing is here you will see
that I'm useing that same name from the unleveled file that because I am
having all //new file goto a new fuolder that script makes with the -o.
del /f /q %file% // here we delete the file we just leveled and start the
looop all over till all the files in that file is done.
goto top

**Comment by slhck** [comment]
I was going to format this using Markdown but it does not seem like proper batch file syntax.

But I guess for a simple loop, this should suffice:

```bat
for %%a in ("*.*") do ffmpeg-normalize "%%a"
```

See also: https://forum.videohelp.com/threads/356314-How-to-batch-convert-multiplex-any-files-with-ffmpeg

**Comment by michaelcrossland** [comment]
if you want it to be stripped down just remove all text after the // in the
bats I put up there. I use the // in front of any comments I put in as
CMD.exe don't really have a comments like other scripting lag do. In batch
files REM is a remark but that has to be put at the front of the line
otherwise CMD try's to run it a a file name or variable. as for what you
got there. that will not work if your running windows 8 -10. Due to changes
MS Made to CMD and how it handles file paths. what you want is something
like this.

FOR %%i in ("*.mp4") DO ffmpeg-normalize -o -u -v -l -27 -a aac -e "-ac 2
-b:a 96k" "%%~nxi"
You have to give CMD at least a part of the file name or give it a ext to
use. I d the ext most of the time. And use the %%~nxi where your file name
goes to other wise CMD will try ti fill in the full long patch into the
file. with %%~nxi it just put the filename and ext in to it to be used.
