### ISSUE TITLE
How do I run this against multiple files and run through subdirectories?

### ISSUE THREAD

**Issue by Saltystew** [slhck/ffmpeg-normalize#32]
I'm a little confused on how to run it against multiple files at one time, I thought all I needed to do was *.mp4 if I wanted to normalize all mp4 files in a directory but it just does this

![shot_170727_040045](https://user-images.githubusercontent.com/20447447/28660230-325120e4-7280-11e7-9512-5e5108e10cdf.png)

**Comment by slhck** [comment]
This syntax works on Bash and similar shells.

Is this Windows PowerShell? I don't have a Windows system to test this with.

**Comment by michaelcrossland** [comment]
You got to remember that yes window's powershell is much closer to a *inux
box CL. But it still uses windows old bat file systex in the way works. Or
the new PS systex. So to run it on multiple files use this.

for /F %%a in ("*.mp4") do set FileName="%%~nxa"
Set FileName2=%FileName: "=℅
For /F "delims=" %%A in ("%FileName2%") do set FileName3=%%~nxA
ffmpeg-normalize -u -v -l -27 -a aac -e "-b:a 96k" "%FileName3%"

Now that is meant to be ran from batch file or .bat file. Now if you want
run it from the PS then remove the %% and just use one % not two.
Hope this help's if need more help fell free to replay back.
You're friend in coding,
Michael

**Comment by slhck** [comment]
Thanks, Michael, for providing the code.

**Comment by michaelcrossland** [comment]
You're welcome. Glade it could help you.

**Comment by Saltystew** [comment]
Is it necessary that I re-encode the audio to a specific bitrate? I'm using this on video files and it seemed to not mess with the bitrate when I left it alone.

**Comment by michaelcrossland** [comment]
No I just do it to save space. As most the stuff I get is in mp3 audio or a
much higher bit rate aac audio. So by doing that on mp3 video audio i can
get some where from 45% to 75% smaller video size. Without losing any audio
 quality. As for the aac based videos I get about 10% to 24% in file size
reduction.
As of right now I have over almost 6 month's viewing time moves and over 5
years viewing time in TV shows and Nightly News casts. All on a 2 TB NAS
that setup. I still have over 900 GB's of space left. Here be next year
I'll have move to 2 or 3 TB drives to add more space.
But I have been putting stuff on it for over 2 years now. All because I use
a lower bit rate. But you can't tell it's lower even on a 5.1 home setup.
But no you don't have to set the bit rate or the audio codec.
Hope that cleared that up for you.
Your friend in coding,
Michael

Sent form my Samsung Note 3

**Comment by Saltystew** [comment]
Hmm, I'm confused. The bat file opens a cmd and it closes immediately. Pretty sure it's not supposed to do that.

I didn't alert the code you wrote at all, was I suppose to?

**Comment by michaelcrossland** [comment]
Sorry I only put part of the code to help you out. I didn't know you where
looking for a full script.
I would do it but I get paid for doing a full script or program. I'll post
a small bit of code that you need to make it work. But I'm sorry if you
want more it ez to ask the god known as Google I do it all the time about
45 mins or so of reading forums post and guides you should get to work. And
yes you well need to mod some of the code to make it work with your system.
If you don't have ffmpeg listed in your windows system paths. You will have
mod it so that ffmpeg- normalize can find so that it can do it's job.

Sent form my Samsung Note 3

**Comment by slhck** [comment]
> Is it necessary that I re-encode the audio to a specific bitrate? I'm using this on video files and it seemed to not mess with the bitrate when I left it alone.

It depends on your use case. Please note that the default output audio codec is PCM WAV, which is uncompressed, lossless audio. The default was chosen because it does not add any quality degradation compared to the original. It will result in large files (e.g., try normalizing an MP3 file and you will get a resulting file of ~10x the size).

If you want compressed audio output, you should choose a codec like AAC, by adding an extra option. For example:

    ffmpeg-normalize -vu -a aac -e "-b:a 192k" input.mkv

This will re-encode the file using the ffmpeg built-in AAC encoder.

**Comment by slhck** [comment]
As for batch-converting with Windows' shell, you can try something simple like:

    for %%A IN (*.avi) DO ffmpeg-normalize "%%A"

**Comment by michaelcrossland** [comment]
But if you file names have spaces in them. It would be ("*.mp4" )

Sent form my Samsung Note 3

**Comment by michaelcrossland** [comment]
That is why you should always use "" when working with batch file stuff.
That way you don't have to rename everything or have to remember if the
script will work with your file names or not. That's why there are 3 other
things I had before the normalized part. So that the file name and ext are
all that is pasted to the normalize part. Because ffmpeg don't like things
that are double wrapped in quotations. Because of that a lot of times it
will fail and there is no output as the white sale because you're running
in a python shell that does not output to the terminal window.

Sent form my Samsung Note 3
