### ISSUE TITLE
normalize and overwrite same file

### ISSUE THREAD

**Issue by benzkji** [slhck/ffmpeg-normalize#46]
I tried `ffmpeg-normalize --no-prefix -rMP3 --level=-12 --force *.MP3`

to normalize a bunch of files, and just overwrite them after normalizing is done. `ffmpeg-normalize` says `output file is the same as input file, cannot proceed`.  I guess this cannot work because of the design of `ffmpeg` itself?

**Comment by slhck** [comment]
> I guess this cannot work because of the design of ffmpeg itself?

Yes, because it'd need two runs. (It could be implemented using temporary files but this is something for a future version, possibly even a re-write of the script.)

You could use the `-o` / `--dir` option instead of `--no-prefix` and write the files to another directory, then move everything from that directory back to the parent directory.

**Comment by benzkji** [comment]
thx for your fast response, and the workaround. feel free to close this :)

**Comment by slhck** [comment]
No worries, I'll keep it open as a feature for a next version (once I find some more time to write it…).

**Comment by benzkji** [comment]
nice, thx again!

**Comment by slhck** [comment]
It's now possible to do that with version 1.0.

Note that the command-line options have changed a little bit.
