### ISSUE TITLE
Command line flag for specifying the path to ffmpeg

### ISSUE THREAD

**Issue by mdcollins05** [slhck/ffmpeg-normalize#52]
It would be awesome if I could use a flag to set the path to the ffmpeg binary instead of modifying my path temporarily on each run.

**Comment by slhck** [comment]
Would an environment variable like `FFMPEG_PATH` work for you?

Similar to this approach: https://github.com/fluent-ffmpeg/node-fluent-ffmpeg#ffmpeg-and-ffprobe

I'm not against introducing a command-line flag but it seems like environment variables are the go-to solution for “overriding where a program should look for another program”.

**Comment by mdcollins05** [comment]
Yeah, that would be better than modifying $PATH.

**Comment by michaelcrossland** [comment]
Why change anything. Just build ffmpeg from the github repo that gives you
all the tools and scripts you need to build ffmpeg. Just put in your
windows directory. Then you don't have to change anything.

On Jan 29, 2018 9:59 PM, "MDCollins" <notifications@github.com> wrote:

Yeah, that would be better than modifying $PATH.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/slhck/ffmpeg-normalize/issues/52#issuecomment-361469998>,
or mute the thread

**Comment by mdcollins05** [comment]
I do currently use a pre-build binary of ffmpeg because my linux distro doesn't have an updated ffmpeg with loudnorm/EBU R128 support. Personally, I don't want to drop files on my system in directories typically managed by the package manager. I'd prefer an option to simplify things, though setting the PATH temporarily isn't hard to do.

I figure I'd request this feature to make it easier for anyone in a similar situation but I'll leave it up to @slhck as to what option, if any, he would like to implement.

**Comment by michaelcrossland** [comment]
Okay far enough why did you not state that you running a disto of linux to
start with. I thought you where a windows user. My bad. Next time if you
would state what OS your working under you can get better results. Like I
said my bad as my work around wouldn't work out to good for your setup.

**Comment by slhck** [comment]
This is done now. You can specify `FFMPEG_PATH` to override the system path.

**Comment by mdcollins05** [comment]
Awesome. Thanks a ton!
