### ISSUE TITLE
Large files speed up

### ISSUE THREAD

**Issue by xamgore** [slhck/ffmpeg-normalize#73]
I use ffmpeg-normalize to normalize the sound in large files, usually lasting one to two hours, which contain a video track. The process takes approximately 50-80 minutes.

Does the tool copy the video track several times while the EBU is running? Can I speed the process up if I use `--video-disable` option, and then concat audio with video by ffmpeg?

---

Thank you for you tool :)

**Comment by slhck** [comment]
EBU normalization runs in two passes. The video track is completely disabled in the first pass, since that pass only calculates loudness statistics. In the second pass, it's copied over (unless you specify a video encoder with `-c:v`).

Therefore, the duration of the normalization process is dependent on the speed at which the `loudnorm` filter can be run. I'm afraid there's no way of speeding that up.

If you want the process to be faster, you don't have to use `ffmpeg-normalize` (which defaults to two EBU passes) – you can use `ffmpeg` directly. But it'll be not as accurate (see [here](http://k.ylo.ph/2016/04/04/loudnorm.html) for more info):

    ffmpeg -i <input> -c:v copy -filter:a loudnorm -c:a aac -b:a 192k output.mp4

This would encode the audio to AAC at 192 kbit/s, and use single-pass EBU normalization with the default options.
